import 'package:flutter/material.dart';
import 'package:labyrinth_maker/barrier/horizontal_barrier.dart';
import 'package:labyrinth_maker/barrier/vertical_barrier.dart';
import 'package:labyrinth_maker/cell.dart';

class Board extends StatelessWidget {
  const Board({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return AspectRatio(
      aspectRatio: 1,
      child: Container(
        padding: const EdgeInsets.all(10),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: const <Widget>[
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
              ],
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: const <Widget>[
                SizedBox(width: 3),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                SizedBox(width: 3),
              ],
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: const <Widget>[
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
              ],
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: const <Widget>[
                SizedBox(width: 3),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                SizedBox(width: 3),
              ],
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: const <Widget>[
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
              ],
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: const <Widget>[
                SizedBox(width: 3),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                SizedBox(width: 3),
              ],
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: const <Widget>[
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
              ],
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: const <Widget>[
                SizedBox(width: 3),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                SizedBox(width: 3),
              ],
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: const <Widget>[
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
              ],
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: const <Widget>[
                SizedBox(width: 3),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 2, child: HorizontalBarrier(isOccupied: false)),
                SizedBox(width: 3),
              ],
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: const <Widget>[
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
                Spacer(),
                Flexible(flex: 2, child: VerticalBarrier(isOccupied: false)),
                Spacer(),
                Flexible(flex: 12, child: Cell()),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
